### ISSUE TITLE
Fails to compile, multiple definition of loop and setup

### ISSUE THREAD

**Issue by flufftronix** [doctea/usb_midi_clocker#1]
Hiya, I was hoping to give this a go but am getting some errors when compiling either on Windows or Arch.

In both cases, I get up to `Linking .pio\build\teensy41\firmware.elf` without any errors or warnings and then get there errors. They're the same on each platform except for the path and executable, Win11 version:

```
.pio\build\teensy41\src\usb_midi_clocker.cpp.o: In function `loop':
usb_midi_clocker.cpp:(.text.loop+0x0): multiple definition of `loop'
.pio\build\teensy41\src\main.cpp.o:main.cpp:(.text.loop+0x0): first defined here
c:/users/michael/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions
.pio\build\teensy41\src\usb_midi_clocker.cpp.o: In function `setup':
usb_midi_clocker.cpp:(.text.setup+0x0): multiple definition of `setup'
.pio\build\teensy41\src\main.cpp.o:main.cpp:(.text.setup+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\teensy41\firmware.elf] Error 1
```

Any ideas as to what might be going on?

**Comment by doctea** [comment]
Hi!  Thanks for being the first brave person (that I know of, anyway!) to give this a try.  Sorry you've stumbled at the first hurdle!  Let's see if we're able to get it at least compiling for you.

I notice that your linker seems to be using a file `.pio\build\teensy41\src\main.cpp.o`.  There is no 'main.cpp' in the src folder of this project (src/usb_midi_clocker.cpp contains loop() and setup(), etc).. My first thought is that you have ended up with a rogue main.cpp in the src folder, for some reason?  Wondering if perhaps you have an extension installed in vscode (.. which I presume is what you're using?) that has added its own main.cpp in an effort to import the code?

If you find that you do have a file src/main.cpp in the project folder then show me what it contains and we can try and figure out where its come from.

Please check for that and let me know how you get on!  If you have any other information about your environment (what extensions you have installed etc) then that might also be helpful.

Even when if we get this fixed then there will almost certainly be other things that will need fixing or that I'll need to help you with configuring, but I'd thrilled to see someone else using this! :)

**Comment by flufftronix** [comment]
Ah! Yep. I had git clone'd this project and then added it in platform.io, which added a boilerplate main.cpp file:

```
#include <Arduino.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```
As those are the duplicate functions in question, deleting that main.cpp file fixes the errors.

Will try and get this running on my teensy soon, I'll let you know how that goes (and I'm already using same DeftAudio board with a 2" ST7789, but this seems waaay father along than I'd gotten poking at the sample code so far). Thanks!
